# Generated by Django 5.0 on 2023-12-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais_origen',
            field=models.CharField(blank=True, choices=[('pais1', 'Argentina'), ('pais2', 'Brasil'), ('pais3', 'Serbia'), ('pais4', 'Kiribati'), ('pais5', 'Italia'), ('pais6', 'Sudán'), ('pais7', 'Australia'), ('pais8', 'Islas Feroe'), ('pais9', 'Marruecos'), ('pais10', 'Egipto')], max_length=50, null=True),
        ),
    ]
