# Generated by Django 5.0 on 2023-12-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_delete_pais_remove_cliente_pais_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
