# Generated by Django 5.0 on 2023-12-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_rename_product_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cat1', 'Servicios'), ('cat2', 'Escapes'), ('cat3', 'Motor'), ('cat4', 'Chasis'), ('cat5', 'Baterías')], max_length=50),
        ),
    ]
