# Generated by Django 5.0 on 2023-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_categorias_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
