# Generated by Django 5.0 on 2023-12-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
